server:
  port: 8090
management:
  port: 8762
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    metadataMap:
      management-url: http://localhost:${management.port}
      management-port: ${management.port}
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    hostname: localhost
  server:
    waitTimeInMsWhenSyncEmpty: 0